---
_extends: .github

repository:
  name: hs-cimple
  description: Cimple and Apidsl language parsers and tools
  topics: c, dsl, parser

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "Cabal Build / build (pull_request)"
          - "cirrus-ci"
          - "Codacy Static Code Analysis"
          - "code-review/reviewable"
