---
_extends: .github

repository:
  name: hs-cimple
  description: Cimple and Apidsl language parsers and tools
  topics: c, dsl, parser

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - cirrus-ci
          - code-review/reviewable
